spring:
  application:
    name: shipping_fee

server:
  port: 8080
# GHTK Configuration
ghtk:
  api:
    # API Token From GHTK
    token: "4658225d-ff62-11f0-bc77-e205e6d9b297"
    # Shop ID
    shop-id: 5158895
    # Test
    base-url: https://dev-online-gateway.ghn.vn  
    # base-url: https://online-gateway.ghn.vn   # Production

logging:
  level:
    com.example.shipping_fee: DEBUG
    root: INFO
