spring:
  application:
    name: shipping_fee

server:
  port: 8080
# GHN Configuration
ghtk:
  api:
    # API Token From GHN
    token: "4658225d-ff62-11f0-bc77-e205e6d9b297"
    # Shop ID
    shop-id: 6250039
    # Production URL (token này là production token)
    base-url: https://online-gateway.ghn.vn
    # base-url: https://dev-online-gateway.ghn.vn   # Test

logging:
  level:
    com.example.shipping_fee: DEBUG
    root: INFO
